import type { Metadata } from "next";
import "./globals.css";
import { RootLayout } from "./component/shared/RootLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="satoshi-variable">
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
